name: Docker Image 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
    MONOGODB_URI: ${{ secrets. MONOGODB_URI }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t emp .
    - name: Tag the Docker image
      run: docker tag emp Roopaskumar7/Task-1-Elevate-Labs
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run: docker push Roopaskumar7/Task-1-Elevate-Labs
      
      
