name: Docker Image 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MONGODB_URI:  ${{ secrets.MONGODB_URI }}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t emp .
    - name: Tag the Docker image
      run: docker tag emp roopaskumar/task1elevatelabs
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run: docker push  roopaskumar/task1elevatelabs
